<?php
$menus = array();

foreach($this->menus as $menu) {
    $curMenu = array(
        'id'    => $menu->getId(),
        'label' => $menu->getLabel(),
        'uri'   => $menu->getUri(),
        'order' => $menu->getPosition(),
    );

    if($menu->getParentId() != 0) { // somebody's child
        $menus[$menu->getParentId()]['pages'][] = $curMenu;
    } else {
        if(isset($menus[$menu->getId()]['pages'])) {
            $pageData = $menus[$menu->getId()]['pages'];
        } else {
            $pageData = array();
        }
        $menus[$menu->getId()] = array_merge($curMenu, array('pages' => $pageData));
    }
}

$container = new Zend_Navigation($menus);
$this->navigation($container);
//$this->navigation()->menu()->setPartial('partials/_menu-left-row.phtml');

$activeNav = $this->navigation()->findByUri($this->selectedUri);
$activeNav->active = true;
if(is_callable(array($activeNav, 'setClass'))) {
    $activeNav->setClass("active");
}

echo $this->navigation()->menu();