<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../application/models/Page.php';

/**
 * Test class for Model_Page.
 * Generated by PHPUnit on 2010-05-04 at 14:08:57.
 */
class Model_PageTest extends PHPUnit_Framework_TestCase {
    /**
     * @var    Model_Page
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
//        require_once APPLICATION_PATH . '/models/PageMapper.php';
//        require_once APPLICATION_PATH . '/models/PageRouter.php';
//        require_once APPLICATION_PATH . '/../library/Zend/Db/Table/Abstract.php';
//        $this->object = new Model_Page;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testFetchAll().
     */
    public function testFetchAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFind().
     */
    public function testFind() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testUpdate().
     */
    public function testUpdate() {
        $this->assertEquals(true, true);
        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
    }

    /**
     * @todo Implement testCreate().
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
