<div id="toolbar-box">
    <div class="t">
        <div class="t">
            <div class="t"></div>
        </div>
    </div>
    <div class="m">
        <div id="toolbar" class="toolbar-list">
            <?php
            echo $this->placeholder('toolbar-list');
            ?>
            <div class="clr"></div>
        </div>
        <?php
        echo $this->placeholder('pagetitle');
        ?>
        <div class="clr"></div>
    </div>
    <div class="b">
        <div class="b">
            <div class="b"></div>
        </div>
    </div>
</div>
<div class="clr" ></div>

