<?php
if($this->toolbar_active === true) {
    echo $this->render('global/_toolbar.phtml');
}

if($this->submenu_active === true) {
    echo $this->render('global/_submenu.phtml');
}

if($this->error_active === true) {
    echo $this->render('global/_error.phtml');
}
?>
<div id="element-box">
    <div class="t">
        <div class="t">
            <div class="t"></div>
        </div>
    </div>
    <div class="m">
        <?php
        echo $this->placeholder('element-box');
        ?>
    </div>
    <div class="b">
        <div class="b">
            <div class="b"></div>
        </div>
    </div>
</div>