<?php $this->placeholder('toolbar-list')->captureStart();?>
<!-- toolbar list content -->
<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-user">
    <h2> User Manager: Add New User </h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>

<?php echo $this->form; ?>

<?php $this->placeholder('element-box')->captureEnd();?>