<?php $this->placeholder('toolbar-list')->captureStart();?>
<ul>
    <li id="toolbar-new" class="button">
        <a class="toolbar" href="/admin/user/create">
        <span class="icon-32-new"> </span>
        New
        </a>
    </li>
    <li id="toolbar-delete" class="button">
        <a class="toolbar" onclick="javascript:if (document.adminForm.boxchecked.value==0){alert('Please first make a selection from the list');}else{ submitbutton({'action':'delete'})}" href="#">
        <span class="icon-32-delete"> </span>
        Delete
        </a>
    </li>
</ul>
<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-user">
    <h2> User Manager: Users </h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('submenu')->captureStart();?>
<ul id="submenu">
    <li>
    <a class="active" href="/admin/user/list">Users</a>
    </li>
    <li>
    </li>
    <li>
    </li>
</ul>
<?php $this->placeholder('submenu')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>

<form name="adminForm" method="post" action="/admin/user/list">

    <fieldset id="filter-bar">
        <div class="filter-search fltlft">
        <label class="filter-search-lbl" for="filter_search">Search Users:</label>
        <input id="filter_search" type="text" title="Search Users" value="" name="filter_search"/>
        <button type="submit">Search</button>
        <button onclick="document.id('filter_search').value='';this.form.submit();" type="button">Reset</button>
        </div>
        <div class="filter-select fltrt">
        <label for="filter_enabled"> Filter Users by:  </label>
        <select class="inputbox" onchange="this.form.submit()" name="filter_enabled">
            <?php
            $options = array('options' => array(
                '*' => '- State',
                '1' => 'Enabled',
                '0' => 'Disabled'
                ), 'selected' => $this->filter['enabled']
            );
            echo $this->partial('partials/forms/select-options.phtml',
                    array('options' => $options));
            ?>
        </select>
        <select class="inputbox" onchange="this.form.submit()" name="filter_role">
            <?php
            $user_options = array('options' => array(
                '' => '- Group',
                'Administrator' => 'Administrator',
                'User' => 'User'
                ), 'selected' => $this->filter['role']
            );
            echo $this->partial('partials/forms/select-options.phtml',
                    array('options' => $user_options));
            ?>
        </select>
        </div>
    </fieldset>

    <div class="clr"> </div>

    <?php if(sizeof($this->paginator) > 0):?>

    <table class="adminlist">
        <thead>
            <tr>
                <th width="1%">
                    <input type="checkbox" onclick="checkAll(<?=count($this->users)?>)" value="" name="toggle"/>
                </th>
                <th class="left">
                    <a title="Click to sort by this column" href="javascript:tableOrdering('a.name','desc','');">
                    Name
                    <img alt="" src="/_data/admin/system/images/sort_asc.png"/>
                    </a>
                </th>
                <th class="nowrap" width="10%">
                    <a title="Click to sort by this column" href="javascript:tableOrdering('a.username','desc','');">User Name</a>
                </th>
                <th class="nowrap" width="5%">
                    <a title="Click to sort by this column" href="javascript:tableOrdering('a.block','desc','');">Enabled</a>
                </th>
                <th class="nowrap" width="10%"> Groups </th>
                <th class="nowrap" width="15%">
                    <a title="Click to sort by this column" href="javascript:tableOrdering('a.email','desc','');">E-mail</a>
                </th>
                <th class="nowrap" width="15%">
                    <a title="Click to sort by this column" href="javascript:tableOrdering('a.lastvisitDate','desc','');">Last Visit Date</a>
                </th>
                <th class="nowrap" width="15%">
                    <a title="Click to sort by this column" href="javascript:tableOrdering('a.registerDate','desc','');">Registration Date</a>
                </th>
                <th class="nowrap" width="3%">
                    <a title="Click to sort by this column" href="javascript:tableOrdering('a.id','desc','');">ID</a>
                </th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="15">
                    <?php
                    echo $this->paginationControl($this->paginator,
                     'Sliding',
                     'partials/pagination-control.phtml');
                    ?>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?php
            echo $this->partialLoop('partials/_user-row.phtml', $this->paginator);
            ?>
        </tbody>
    </table>
    
    <input type="hidden" name="boxchecked" id="boxchecked" value="0" />

    <?else:?>
        You do not have any users
    <?endif;?>
    
</form>

<?php $this->placeholder('element-box')->captureEnd();?>
