<div class="padding">
    <div class="clr"></div>
    <div id="element-box" class="login">
        <div class="t">
            <div class="t">

                <div class="t"></div>
            </div>
        </div>
        <div class="m wbg">
            <h1>Administration Login</h1>

                    <div id="section-box">
    <div class="t">
        <div class="t">
            <div class="t"></div>
        </div>
    </div>
    <div class="m">
            <!-- login form -->
            <?php if($this->loginMessage) { ?>
            <p><?php echo $this->loginMessage?></p>
            <?php }
            echo $this->form;
            ?>
            <!-- //login form -->
        <div class="clr"></div>
    </div>
    <div class="b">
        <div class="b">
            <div class="b"></div>
        </div>
    </div>
</div>

            <p>Use a valid username and password to gain access to the administrator backend.</p>

            <p><a href="/">Go to site home page.</a></p>
            <div id="lock"></div>
            <div class="clr"></div>
        </div>
        <div class="b">
            <div class="b">
                <div class="b"></div>
            </div>

        </div>
    </div>
    <noscript>
        Warning! JavaScript must be enabled for proper operation of the Administrator backend.			</noscript>
    <div class="clr"></div>
</div>