<?php $this->placeholder('element-box')->captureStart();?>
<div class="adminform">
    <div class="cpanel-left">
        <div id="cpanel">
            <div class="icon-wrapper">
                <div class="icon">
                    <a href="/admin/page">
                        <img alt="" src="/skins/<?=$this->skin?>/images/header/icon-48-article.png" />
                        <span>Manage Pages</span>
                    </a>
                </div>
            </div>
            <div class="icon-wrapper">
                <div class="icon">
                    <a href="/admin/user/list">
                        <img alt="" src="/skins/<?=$this->skin?>/images/header/icon-48-user.png" />
                        <span>Manage Users</span>
                    </a>
                </div>
            </div>
            <div class="icon-wrapper">
                <div class="icon">
                    <a href="/admin/news">
                        <img alt="" src="/skins/<?=$this->skin?>/images/header/icon-48-news.png" />
                        <span>Manage News</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clr"></div>
<?php $this->placeholder('element-box')->captureEnd();?>