<?php $this->placeholder('toolbar-list')->captureStart();?>
<ul>
    <li id="toolbar-new" class="button">
        <a class="toolbar" href="/admin/menu/create">
        <span class="icon-32-new"> </span>
        New
        </a>
    </li>
</ul>
<?php $this->placeholder('toolbar-list')->captureEnd();?>

<?php $this->placeholder('pagetitle')->captureStart();?>
<div class="pagetitle icon-48-menumgr">
    <h2> Menu Manager: Menus </h2>
</div>
<?php $this->placeholder('pagetitle')->captureEnd();?>

<?php $this->placeholder('submenu')->captureStart();?>
<ul id="submenu">
    <li>
        <a class="active" href="/admin/menu">Menus</a>
    </li>
    <li>
        <a href="/admin/menuitem">Menu Items</a>
    </li>
</ul>
<?php $this->placeholder('submenu')->captureEnd();?>

<?php $this->placeholder('element-box')->captureStart();?>

<form name="adminForm" method="post" action="/admin/menu">
    <table class="adminlist">
        <thead>
            <tr>
                <th width="1%" rowspan="2">
                    <input type="checkbox" onclick="checkAll(this)" value="" name="toggle"/>
                </th>
                <th rowspan="2">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'menu',
                    'action' => 'index'
                 ), 'title');?>">Title
                    <?php
                    echo $this->getSortImage('title');
                    ?>
                    </a>
                </th>
                <th width="50%" colspan="3"> Number of Menu Items </th>
                <th class="nowrap" width="1%" rowspan="2">
                    <a title="Click to sort by this column" href="<?php echo $this->getUrlReverseSorting(array(
                    'module' => 'admin',
                    'controller' => 'menu',
                    'action' => 'index'
                 ), 'id');?>">ID
                    <?php
                    echo $this->getSortImage('id');
                    ?>
                    </a>
                </th>
            </tr>
            <tr>
                <th width="10%"> # Published </th>
                <th width="10%"> # Unpublished </th>
                <th width="10%"> # Trashed </th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="15">
                    <?php
                    echo $this->paginationControl($this->paginator,
                     'Sliding',
                     'partials/pagination-control.phtml');
                    ?>
                </td>
            </tr>
        </tfoot>
        <tbody>
            <?php
            echo $this->partialLoop('partials/_menu-row.phtml', $this->paginator);
            ?>
        </tbody>
    </table>
</form>
<?php $this->placeholder('element-box')->captureEnd();?>