<tr class="row<?php echo $this->partialCounter % 2 == 0 ? 1 : 0?>">
    <td class="center">
        <input id="cb0" type="checkbox" title="Checkbox for row 1" onclick="isChecked(this.checked);" value="2" name="cid[]"/>
    </td>
    <td>
        <a href="/admin/menuitem"><?=$this->menuItem->getTitle()?></a>
        <p class="smallsub">
            (
            <span>Menu Type:</span>
            <a href="/admin/menu/edit/id/<?=$this->menuItem->getId()?>"><?=$this->menuItem->getMenutype()?></a>
            )
        </p>
    </td>
    <td class="center btns">0</td>
    <td class="center btns">0</td>
    <td class="center btns">0</td>
    <td class="center"><?=$this->menuItem->getId()?></td>
</tr>