<tr class="row<?php echo $this->partialCounter % 2 == 0 ? 1 : 0?>">
    <td class="center">
        <input id="cb0" type="checkbox" title="Checkbox for row <?=$this->partialCounter?>" onclick="isChecked(this.checked);" value="<?=$this->id?>" name="cid[]"/>
    </td>
    <td>
        <?=str_repeat('&nbsp;', ($this->level - 1) * 3)?>
        <a href="/admin/menuitem/edit/id/<?=$this->id?>"> 
            <?=$this->escape($this->label)?>
        </a>
    </td>
    <td class="center">
        <?php
        if($this->published) {
            $action = 'Unpublish Item';
            $text = 'Published';
            $state = 'publish';
        } else {
            $action = 'Publish Item';
            $text = 'Unpublished';
            $state = 'unpublish';
        }
        ?>
        <a class="jgrid" title="<?=$action?>" onclick="return listItemTask('cb0','articles.unpublish')" href="javascript:void(0);">
        <span class="state <?=$state?>">
            <span class="text"><?=$text?></span>
        </span>
        </a>
    </td>
    <td class="order">
        <span> </span>
        <span>
        <span class="jgrid" title="Move Down">
        <span class="state downarrow_disabled">
        <span class="text">Move Down</span>
        </span>
        </span>
        </span>
        <input class="text-area-order" type="text" disabled="disabled" value="<?=$this->position?>" size="5" name="order[]"/>
    </td>
    <td class="center"> <?=$this->menu_id?> </td>
    <td class="center"> <?=$this->id?> </td>
</tr>