<tr id="node-<?=$this->escape($this->name)?>">
    <td>
        <a href="javascript:void(0)" onclick="showNode('<?=$this->escape($this->name)?>', <?=$this->pageId?>)">
            <?=$this->escape($this->name)?>
        </a>
    </td>
    <td>
        <a href="javascript:void(0)" title="Copy Node To All Pages" onclick="copyNodeToAllPages('<?=$this->escape($this->name)?>', <?=$this->pageId?>); return false;">
            <img src="/_data/admin/system/images/copy.png" alt="Copy Node To All Pages" />
        </a>
    </td>
    <td>
        <a href="javascript:void(0)" title="Delete Node" onclick="deleteNode('<?=$this->escape($this->name)?>', <?=$this->id?>); return false;">
            <img src="/_data/admin/system/images/delete.png" alt="Delete Node" />
        </a>
    </td>
</tr>