<div class="noshow">
    <div class="width-60">
        <fieldset class="adminform">
            <legend>Relevant PHP Settings</legend>
            <table class="adminlist">
                <thead>
                    <tr>
                        <th width="250"> Setting </th>
                        <th> Value </th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <td colspan="2">  </td>
                    </tr>
                </tfoot>
                <tbody>
                    <tr>
                        <td> Safe Mode: </td>
                        <td> <?=$this->sysInfo->phpSetting('safe_mode')?> </td>
                    </tr>
                    <tr>
                        <td> Open basedir: </td>
                        <td> <?=$this->sysInfo->phpSetting('open_basedir')?> </td>
                    </tr>
                    <tr>
                        <td> Display Errors: </td>
                        <td> <?=$this->sysInfo->phpSetting('display_errors')?> </td>
                    </tr>
                    <tr>
                        <td> Short Open Tags: </td>
                        <td> <?=$this->sysInfo->phpSetting('short_open_tag')?> </td>
                    </tr>
                    <tr>
                        <td> File Uploads: </td>
                        <td> <?=$this->sysInfo->phpSetting('file_uploads')?> </td>
                    </tr>
                    <tr>
                        <td> Magic Quotes: </td>
                        <td> <?=$this->sysInfo->phpSetting('magic_quotes_gpc')?> </td>
                    </tr>
                    <tr>
                        <td> Register Globals: </td>
                        <td> <?=$this->sysInfo->phpSetting('register_globals')?> </td>
                    </tr>
                    <tr>
                        <td> Output Buffering: </td>
                        <td> <?=$this->sysInfo->phpSetting('output_buffering')?> </td>
                    </tr>
                    <tr>
                        <td> Session Save Path: </td>
                        <td> <?=$this->sysInfo->phpSetting('session.save_path')?> </td>
                    </tr>
                    <tr>
                        <td> Session Auto Start: </td>
                        <td> <?=$this->sysInfo->phpSetting('session.auto_start')?> </td>
                    </tr>
                    <tr>
                        <td> XML Enabled: </td>
                        <td> <?=$this->sysInfo->phpSetting('xml')?> </td>
                    </tr>
                    <tr>
                        <td> Zlib Enabled: </td>
                        <td> <?=$this->sysInfo->phpSetting('zlib')?> </td>
                    </tr>
                    <tr>
                        <td> Disabled Functions: </td>
                        <td> <?=$this->sysInfo->phpSetting('disable_functions')?> </td>
                    </tr>
                    <tr>
                        <td> Mbstring Enabled: </td>
                        <td> <?=$this->sysInfo->phpSetting('mbstring')?> </td>
                    </tr>
                    <tr>
                        <td> Iconv Available: </td>
                        <td> <?=$this->sysInfo->phpSetting('iconv')?> </td>
                    </tr>
                </tbody>
            </table>
        </fieldset>
    </div>
</div>