<tr class="row<?php echo $this->partialCounter % 2 == 0 ? 1 : 0?>">
    <td class="center">
    <input id="cb0" type="checkbox" title="Checkbox for row 1" onclick="isChecked(this.checked);" value="44" name="cid[]"/>
    </td>
    <td>
    <a title="Edit User <?=$this->escape($this->username)?>" href="/admin/user/update/id/<?=$this->id?>"> <?=$this->escape($this->username)?></a>
    </td>
    <td class="center"> <?=$this->escape($this->username)?> </td>
    <td class="center">
    <a class="grid_true hasTip" href="#toggle" rel="{id:'cb0', task:'users.block'}"/>
    </td>
    <td class="center">
    <a class="grid_true" rel="{id:'cb0', task:''}"/>
    </td>
    <td class="center">
    Editor
    <br/>
    Shop Suppliers
    <br/>
    Customer Group
    </td>
    <td class="center"> <?=$this->email?> </td>
    <td class="center"> <?=intval($this->lastvisitDate) == 0 ? 'Never' : $this->lastvisitDate?> </td>
    <td class="center"> <?=$this->registerDate?> </td>
    <td class="center"> <?=$this->id?> </td>
</tr>