<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php
    echo $this->headTitle();
    echo $this->headScript();
    // add a link to the site style sheet
    //$this->headLink()->appendStylesheet('/css/layout.css');
    $this->loadSkin($this->skin);
    echo $this->headLink();
	echo $this->headMeta();
    ?>
</head>
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
<td height="151" align="left" valign="top" background="/_data/frontend/images/top_bg.png">
	  
<table width="100%" border="0" cellspacing="0" cellpadding="0" background="/_data/frontend/images/top_bg.png">
        <tr><td width="520" rowspan="2" align="left"><img src="/_data/frontend/images/top01.png" width="520" height="151"></td>
<td><img src="/_data/frontend/images/logo1.png" width="74" height="80"></td><td align="left">&nbsp; </td> </tr>
<tr><td align="left" valign="top"><img src="/_data/frontend/images/headline1.png" width="74" height="71" /></td>
    <td>
        <div align="right">
                  <!--<h3><a href="/finishingwork.htm">Отделочные работы в Казани</a>:
                    <br>
                    <strong>8(950)320 6906</strong></h3>-->
                  <?php echo $this->layout()->sidebar?>
        </div>
    </td>
</tr>
</table>

</td></tr>
<tr><td align="left" valign="top" bgcolor="F1F2F3">

<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
<tr> <td width="201" height="531" align="left" valign="top" bgcolor="DCE0E3">

<table width="201" border="0" cellspacing="0" cellpadding="0"  >
 <tr> <td colspan="2"><img src="/_data/frontend/images/search01.png" width="201" height="12"></td> </tr>
 <tr> <td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>
 <tr> <td width="191"   > <p class="menu"> <img src="/_data/frontend/images/dot2.png" width="18" height="12"><a href="/">На главную </a></p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" > </td> </tr>
<tr><td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>
<tr><td width="191"><p class="menu"><img src="/_data/frontend/images/dot2.png" width="18" height="12"><a href="/buildup.htm">Подготовительные
                    работы</a> </p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" > </td> </tr>
<tr><td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>
<tr><td width="191"   ><p class="menu"> <img src="/_data/frontend/images/dot2.png" width="18" height="12"><a href="/buildingwork.htm">Строительные
                    работы</a> </p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" > </td> </tr>
<tr> <td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>
<tr><td width="191"   ><p class="menu"><img src="/_data/frontend/images/dot2.png" width="18" height="12"><a href="/finishingwork.htm">Отделочные
                    работы</a></p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" ></td></tr>
<tr> <td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>
<tr><td width="191"  ><p class="menu"><img src="/_data/frontend/images/dot2.png" width="18" height="12"><a href="/painting.htm">Малярные
                    работы</a> </p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" > </td> </tr>
<tr> <td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>
<tr><td width="191"  > <p class="menu"><img src="/_data/frontend/images/dot2.png" width="18" height="12"><a href="/carpenter.htm">Столярные
                    работы</a></p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" > </td> </tr>
<tr><td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>
<tr><td width="191"   > <p class="menu"><img src="/_data/frontend/images/dot2.png" width="18" height="12"><a href="/electric.htm">Электромонтажные
                    работы</a></p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" > </td> </tr>
<tr> <td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>
<tr><td width="191"  > <p class="menu"><img src="/_data/frontend/images/dot2.png" alt="О нас" width="18" height="12"><a href="/sanitary.htm">Сантехнические
                    работы</a></p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" > </td> </tr>
<tr> <td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>
<tr><td width="191" ><p class="menu"><img src="/_data/frontend/images/dot2.png" alt="О нас" width="18" height="12"><a href="/front.htm">Фасадные
                    работы</a> </p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" > </td> </tr>
<tr> <td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>
<tr><td width="191"  > <p class="menu"><img src="/_data/frontend/images/dot2.png" alt="О нас" width="18" height="12"><a href="/roof.htm">Кровельные
                    работы</a> </p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" > </td> </tr>
<tr> <td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>		  <tr><td width="191"  > <p class="menu"><img src="/_data/frontend/images/dot2.png" alt="О нас" width="18" height="12"><a href="/weld.html">Сварочные работы по металлу</a> </p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" > </td> </tr>
<tr> <td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>
<tr><td width="191"  > <p class="menu"><img src="/_data/frontend/images/dot2.png" alt="О нас" width="18" height="12"><a href="/cleaning.htm">Вспомогательные
                    работы </a> </p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" > </td> </tr>
<tr> <td colspan="2"><img src="/_data/frontend/images/white.png" width="201" height="1"></td>  </tr>
<tr><td width="191"   > <p class="menu"><img src="/_data/frontend/images/dot2.png" alt="О нас" width="18" height="13"><a href="/contacts.htm">Контакты</a></p></td>
<td background="/_data/frontend/images/but02_3.png" width="10" ></td> </tr>
<tr> <td colspan="2"><img src="/_data/frontend/images/but07.png" width="201" height="29"></td> </tr>
</table>

</td>
<td width="100%" align="center" valign="top" bgcolor="#FFFFFF"><div align="right"><br>
    <!-- основной текст -->
    <?php echo $this->layout()->content?>
</td>

<td align="left" valign="top" bgcolor="F1F2F3"><table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr><td height="11" valign="top" background="/_data/frontend/images/right_topbg.png"><img src="/_data/frontend/images/right_top.png" width="250" height="11"></td></tr>
</table>
<!-- рекламный и новостной блок -->
<table width="250" border="0" cellspacing="0" cellpadding="0">
<tr><td align="center" valign="top">
<table width="200" border="0" cellpadding="0" cellspacing="0" class="text">
<tr> <td>&nbsp;</td> </tr>
<tr> <td><img src="/_data/frontend/images/side_pic.png" width="207" height="121"></td> </tr>
</table>
<br>

<table width="201" border="0" cellpadding="0" cellspacing="0" class="text">
                    <tr>
                      <td valign="top">
                        <h3> <a href="/../index.htm">Ремонтные
                          и<strong> отделочные работы в Казани</strong> и ближайших
                          пригорода</a>х<br>
                        </h3>
                      </td>
</tr>
  <tr>
                      <td valign="top">
                           <u>
                        <h3> <a href="/moskit.htm">Москитные сетки SKS Stakusit
                          (Германия)</a></h3>
                        </u></td>
</tr>
<tr>
                      <td valign="top">
                     <script type="text/javascript">
var begun_auto_pad = 129170638;
var begun_block_id = 129172620;
</script>
<script src="http://autocontext.begun.ru/autocontext2.js" type="text/javascript"></script></td>
</tr>



</table>
<p>&nbsp;</p></td>
</tr>
</table>
</td></tr>
</table></td>
</tr> <tr>
<td height="15" align="left" valign="top" bgcolor="F1F2F3">
<table width="770" border="0" cellspacing="0" cellpadding="0">
        <tr><td width="201" valign="bottom"><img src="/_data/frontend/images/left_bottom.png" width="201" height="15"></td>
          <td width="319" bgcolor="#FFFFFF" background="/_data/frontend/images/spaser.gif"><img src="/_data/frontend/images/spaser.gif" width="319" height="15"></td>
<td width="250" align="left" valign="bottom"><img src="/_data/frontend/images/right_bg.png" width="250" height="15"></td>
</tr>
</table></td>
</tr>
<tr><td height="23" align="left" valign="top" background="/_data/frontend/images/bottom_barbg.png"><img src="/_data/frontend/images/bottom_bar.png" width="770" height="23"></td>
    </tr>
<tr><td height="61" background="/_data/frontend/images/bottom_bg.png">
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="text">
<tr> <td width="10" height="61" rowspan="2" align="left" valign="top"><img src="/_data/frontend/images/spaser.gif" width="10" height="61"></td>
          <td height="30" class="menuf"  > <a href="/news.htm">новости</a> l l
            <a href="/catalog_links.htm">каталог полезных ссылок</a> l l <a href="/contacts.htm">контакты</a></font></td>
</tr>
<tr>
 <td height="33" >

			<table width="100%" height="33"  border="0" cellpadding="3" cellspacing="3">
              <tr>
			  <td width="31"><!-- begin of Top100 code -->
<script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?1738803"></script><noscript><img src="http://counter.rambler.ru/top100.cnt?1738803" alt="" width="1" height="1" border="0"></noscript>
<!-- end of Top100 code -->&nbsp;</td>
                 <td height="31"align="left" class="copyright"><a href="/http://www.tatdom.ru/">&copy;<?=date("Y")?> TatDom.ru сервис</a><a href="/mailto:elberet-1970@yandex.ru"><br>
                </a><a href="/http://www.tatdom.ru/">                  </a>  <a href="/mailto:elberet-1970@yandex.ru">Связаться по вопросам ф ункционирования сайта, продвижения и<br>
                размещения рекламы:  elberet-1970@yandex.ru</a></p></td>

    <td align="right"><!-- begin of Top100 logo -->
<a href="/http://top100.rambler.ru/top100/"><img src="http://top100-images.rambler.ru/top100/banner-88x31-rambler-gray2.gif" alt="Rambler's Top100" width="88" height="31" border="0" /></a>
<!-- end of Top100 logo --></td>

                <td width="31" height="31" >
                  <!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a href='http://www.liveinternet.ru/click' "+
"target=_blank><img src='http://counter.yadro.ru/hit?t42.3;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";"+Math.random()+
"' alt='' title='LiveInternet' "+
"border=0 width=31 height=31><\/a>")//--></script><!--/LiveInternet--></td>
 <td width="31">&nbsp;</td>
  </tr>
</table>

			 </td>
</tr>
</table></td></tr>
</table>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-9375960-2");
pageTracker._trackPageview();
} catch(err) {}</script></body>
<?php
$this->addScriptPath(APPLICATION_PATH . '/views/scripts');
echo $this->render('util/profiler.phtml');
?>
</html>
